language: node_js
matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode8.3
    node_js: 7
  - os: linux
    node_js: 7
    env:
    - CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache: yarn
addons:
  apt:
    packages:
    - rpm
    - bsdtar
before_script:
- yarn lint
script:
- yarn dist
- ./scripts/test.sh
