language: node_js
matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode8.3
    node_js: 7
  - os: linux
    node_js: 7
    env:
    - CC=clang CXX=clang++ npm_config_clang=1
    compiler: clang
cache: yarn
addons:
  apt:
    packages:
    - rpm
    - bsdtar
before_script:
- yarn lint
script:
- yarn dist
- ./scripts/test.sh
env:
  global:
  - secure: TfPi7MRH4Aj1/GDAeAH5ziZ+YOwoBES4JZK44sAj50FYq/MW/BJ7OPyqsmFFzEvBSW0iBcwuE0+j1zmFmwDAyM7LbctnTHZ82xrNd5VET0dsg17Ff1CPJRLteGI5XlwuLjh/KsLg/XJY2T1gJAE4vtlACG/OVau2FIiELlIDUWa3a2zPO4cHHQvNRhvpDnCdzggyU2wLlmQGcEs2uBTPH+FRyRWNjN/XqRDFs4aY8sHxZOf4VCpOvm3ZHK8jWjGnUzIAwveMPpoQQfkp03m3TJOoPAYeAs/ISgy856Qkb7SPHc6lAqnsyceTskFlOi72f1hHUoxmUt25H4hwC+7H2Is7zRaWI6ganK/dHMdWerWKTc0K/MEmX45UtXCexc6liutzt61Uj8Z7RfnryWxM6acR5HyKxSqkUvTetaJwjn/ee2EFsIfNtYXOYPhsSoC980RedetOKKaRbwCG18paLAagjyYNEOE9wEwagc8FSrW6xZdma6TWLvcyknL1DLwgN1G9IlCCJTQzpNM4Cn8o0DXYIYW6JZ0BT+5QEh5/xdF0fINZ1W3AWRGB//VnSO8GeRkSe8wrnIZemCFC8LrF/aHlc0yXqBrlK2ZLX5tD7KP7y7e3mz2uN8T3i5RfUTg0CYaAXKJsKswaO1IzgBabPfzjDxoIZ8Zb053bovYMqrM=
  - secure: hskZDLLnnGsmspNiyqOvgkG0Ge13Za/jccpuFJyfHVZ3lKmW+fJmPQ/KMLj2ZD/1xjeScoQ2SmGd+YIC2uqx0YtnCBHBWS0vCQKfYBARpvbe07F/DGeyM0tS8YzxUb6tg77RMaqbdKP80gkSq3Lu02WoTCP9HrpITiplF60k9G4yAsVEUSbmkaTJ2r3Lu9xari6smK1W/kGqTbyL2kl6EFjH/Ofen3X16b17XtkYdtZSbUDuR1flIMnxU/aWlmZrPP8LWWpMmY129+9g+dPceaR+Vjl7LmUfghi5ZZ/p5lc238IWv3NJUVj9dH/zaa9RYkHilGIqBSVARlfy5qAgt8Hg7+WqJZEweZXDJRrxMJviwymvkBfscfvEy3/VdPnN5N5PCvWp4OlZ08r/2QjWVoGagjqKxnVn7Y77cRtmUbXRxEJ8AkeHyOEwNrymwRYuTdp3RmehSJIS7HkdTgA54RMssOun+TCwkVSpVCdZ9NUZQdf9SIUyhBokj2Wv9U/MF602uZ6OWN5NBfphp3nVqsDcyikRMwDVuQOg+RTGN0sJwelrF5vcJTRXocFWlqgBt1OgzDqIkgGti4R6uWhKwWhAsEBPFtNrMKpwI8qsd2XHUBuKWULwsdElI888SMwB5DrV5iJnl9YMmzmCFBgWsa9EIEyxkfI9wle1yrZUsYQ=
